language: android

dist: trusty
android:
  components:
    - build-tools-30.0.3
    - android-30

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - wget -P ./godot-google-play-billing/libs https://downloads.tuxfamily.org/godotengine/3.2.4/beta5/godot-lib.3.2.4.beta5.release.aar
  - ./gradlew build -s
